// HAND BATTLE — Theme Effects: Cthulhu / Old One
// 16-4단계: 크툴루/올드원 테마를 EffectDefinition 기반으로 이식한다.
// 핵심 원칙:
// - "소환하고 발동"은 소환을 cost/preActivation으로 처리한다. 무효되어도 코스트는 되돌리지 않는다.
// - 르뤼에는 필드 존 카드이며, 효과로 놓이면 fieldCardActivation 처리를 하지 않는다.
// - 르뤼에 ③은 체인을 만들지 않는 processingNegate다.
// - 아우터 갓은 일반 효과 후보가 아니라 조건이 맞는 procedure/trigger로만 키 카드 덱에서 나온다.
(function initCthulhuEffectDefinitions(global) {
  'use strict';

  const rules = global.HB_RULES || {};
  const EFFECT_TYPES = rules.EFFECT_TYPES || Object.freeze({ ACTIVATION: 'activation', QUICK: 'quick', TRIGGER: 'trigger', CONTINUOUS: 'continuous', PROCEDURE: 'procedure', PROCESSING_NEGATE: 'processingNegate' });
  const ZONES = rules.ZONES || Object.freeze({ DECK: 'deck', HAND: 'hand', PUBLIC_HAND: 'publicHand', FIELD: 'field', FIELD_ZONE: 'fieldZone', GRAVE: 'grave', EXILE: 'exile', KEY_DECK: 'keyDeck' });
  const EVENTS = rules.EVENTS || Object.freeze({ SUMMON: 'summon', SENT_TO_GRAVE: 'sentToGrave', EXILED: 'exiled', CARD_ACTIVATED: 'cardActivated', FIELD_CARD_PLACED: 'fieldCardPlaced' });
  const TIMING = rules.TIMING || Object.freeze({ MY_DEPLOY: 'myDeploy', EITHER_TURN: 'eitherTurn', ON_SUMMON: 'onSummon', ON_SENT_TO_GRAVE: 'onSentToGrave', NONE: 'none' });
  const TAGS = rules.EFFECT_TAGS || Object.freeze({ DECK_SEARCH: 'deckSearch', DECK_SUMMON: 'deckSummon', KEY_DECK_SUMMON: 'keyDeckSummon', HAND_SUMMON: 'handSummon', GRAVE_SUMMON: 'graveSummon', EXILE_SUMMON: 'exileSummon', COST_SEND_TO_GRAVE: 'costSendToGrave', COST_BANISH: 'costBanish', COST_SUMMON: 'costSummon', DRAW: 'draw', DISCARD_HAND: 'discardHand', FIELD_ZONE_EFFECT: 'fieldZoneEffect', PROCESSING_NEGATE: 'processingNegate', NEGATE_EFFECT: 'negateEffect' });

  const registry = global.HB_EFFECT_REGISTRY;
  const zoneAccess = global.HB_ZONE_ACCESS;
  if (!registry) throw new Error('[cthulhu-effects] HB_EFFECT_REGISTRY가 필요합니다.');
  if (!zoneAccess) throw new Error('[cthulhu-effects] HB_ZONE_ACCESS가 필요합니다.');

  const CONTROLLERS = zoneAccess.CONTROLLERS || Object.freeze({ ME: 'me', OPPONENT: 'opponent' });
  const GOO_IDS = Object.freeze(['그레이트 올드 원-크툴루', '그레이트 올드 원-크투가', '그레이트 올드 원-크아이가', '그레이트 올드 원-과타노차']);
  const ELDER_IDS = Object.freeze(['엘더 갓-노덴스', '엘더 갓-크타니트', '엘더 갓-히프노스']);
  const OUTER_IDS = Object.freeze(['아우터 갓 니알라토텝', '아우터 갓-아자토스', '아우터 갓 슈브 니구라스']);

  function getDefaultGameState() { if (typeof G !== 'undefined') return G; return global.G || null; } // eslint-disable-line no-undef
  function getCardDatabase() { if (typeof CARDS !== 'undefined' && CARDS) return CARDS; return global.CARDS || null; } // eslint-disable-line no-undef
  function stateOf(ctxOrState) { return (ctxOrState && ctxOrState.gameState) || ctxOrState || getDefaultGameState(); }
  function getCardId(cardOrId) { if (!cardOrId) return ''; if (typeof cardOrId === 'string') return cardOrId; return cardOrId.id || cardOrId.cardId || ''; }
  function getCardDef(cardOrId) { const cards = getCardDatabase(); const id = getCardId(cardOrId); return cards && id ? cards[id] || null : null; }
  function cardObj(cardId) { const def = getCardDef(cardId) || {}; return { id: cardId, name: def.name || cardId, atk: def.atk || 0, atkBase: def.atk || 0 }; }
  function normalizeController(controller) { return zoneAccess.normalizeController(controller || CONTROLLERS.ME); }
  function my(ctx) { return normalizeController(ctx && ctx.controller); }
  function opp(ctx) { return my(ctx) === CONTROLLERS.ME ? CONTROLLERS.OPPONENT : CONTROLLERS.ME; }
  function zoneArray(ctx, controller, zone) { return zoneAccess.getZoneArray(stateOf(ctx), normalizeController(controller || CONTROLLERS.ME), zone); }
  function field(ctx, controller) { return zoneArray(ctx, controller, ZONES.FIELD); }
  function hand(ctx) { return zoneArray(ctx, my(ctx), ZONES.HAND); }
  function grave(ctx) { return zoneArray(ctx, my(ctx), ZONES.GRAVE); }
  function exile(ctx) { return zoneArray(ctx, my(ctx), ZONES.EXILE); }
  function deck(ctx) { return zoneArray(ctx, my(ctx), ZONES.DECK); }
  function keyDeck(ctx) { return zoneArray(ctx, my(ctx), ZONES.KEY_DECK); }
  function isGOO(c) { return GOO_IDS.indexOf(getCardId(c)) !== -1; }
  function isElder(c) { return ELDER_IDS.indexOf(getCardId(c)) !== -1; }
  function isOuter(c) { return OUTER_IDS.indexOf(getCardId(c)) !== -1; }
  function isOldOne(c) { const id = getCardId(c); const def = getCardDef(id); return id.indexOf('올드_원') !== -1 || id.indexOf('올드 원') !== -1 || id === '태평양 속 르뤼에' || !!(def && (def.theme === '올드원' || def.theme === '크툴루')); }
  function isMonster(c) { const def = getCardDef(c); return !!(def && def.cardType === 'monster'); }
  function hasFieldSpace(ctx, controller) { return ctx.move && ctx.move.hasFieldSpace ? ctx.move.hasFieldSpace(controller || my(ctx)) : field(ctx, controller || my(ctx)).length < 5; }
  function first(list, pred) { return (list || []).find(pred || (x => x)); }
  function findIndexById(list, id) { return (list || []).findIndex(c => getCardId(c) === id); }
  function notifySafe(msg) { try { if (typeof notify === 'function') notify(msg); } catch (_) {} } // eslint-disable-line no-undef
  function logSafe(msg, type) { try { if (typeof log === 'function') log(msg, type || 'mine'); } catch (_) {} } // eslint-disable-line no-undef
  function sync() { try { if (typeof sendGameState === 'function') sendGameState(); } catch (_) {} try { if (typeof renderAll === 'function') renderAll(); } catch (_) {} } // eslint-disable-line no-undef
  function dispatch(ctx) { if (global.HB_EVENTS && typeof global.HB_EVENTS.dispatchEvents === 'function') global.HB_EVENTS.dispatchEvents(ctx.gameState); sync(); }
  function moveById(ctx, fromZone, toZone, cardId, fromController, toController, reason) { return ctx.move.moveCard({ cardId, from: { controller: fromController || my(ctx), zone: fromZone }, to: { controller: toController || my(ctx), zone: toZone }, reason: reason || 'cthulhuEffect' }); }
  function summonFromZone(ctx, cardId, fromZone, reason) { return ctx.move.summonCard({ cardId, from: { controller: my(ctx), zone: fromZone }, reason: reason || 'cthulhuSummon' }); }
  function sendFieldToGrave(ctx, controller, cardId, reason) { return ctx.move.sendToGrave({ cardId, controller, from: { controller, zone: ZONES.FIELD }, reason: reason || 'cthulhuSendToGrave' }); }
  function banishFromDeck(ctx, pred, reason) { const target = first(deck(ctx), pred); if (!target) return false; const r = ctx.move.banishCard({ cardId: getCardId(target), controller: my(ctx), from: { controller: my(ctx), zone: ZONES.DECK }, reason: reason || 'cthulhuBanishDeck' }); if (r && r.ok !== false) logSafe(`${reason || '효과'}: ${getCardId(target)} 제외`, 'mine'); return !!(r && r.ok !== false); }
  function searchToHand(ctx, pred, reason) { const target = first(deck(ctx), pred); if (!target) return false; const r = ctx.move.addToHand({ cardId: getCardId(target), controller: my(ctx), from: { controller: my(ctx), zone: ZONES.DECK }, reason: reason || 'cthulhuSearch' }); if (r && r.ok !== false) logSafe(`${reason || '효과'}: ${getCardId(target)} 패에 넣음`, 'mine'); return !!(r && r.ok !== false); }
  function sendDeckToGrave(ctx, pred, reason) { const target = first(deck(ctx), pred); if (!target) return false; const r = ctx.move.sendToGrave({ cardId: getCardId(target), controller: my(ctx), from: { controller: my(ctx), zone: ZONES.DECK }, reason: reason || 'cthulhuDeckToGrave' }); if (r && r.ok !== false) logSafe(`${reason || '효과'}: ${getCardId(target)} 덱→묘지`, 'mine'); return !!(r && r.ok !== false); }
  function discardOne(ctx, reason) { const c = hand(ctx)[0]; if (!c) return false; const r = ctx.move.discardCard({ cardId: getCardId(c), controller: my(ctx), from: { controller: my(ctx), zone: ZONES.HAND, index: 0 }, reason: reason || 'cthulhuDiscard' }); if (r && r.ok !== false) logSafe(`${reason || '효과'}: ${getCardId(c)} 버림`, 'mine'); return !!(r && r.ok !== false); }
  function sendOwnFieldFirst(ctx, pred, reason) { const t = first(field(ctx, my(ctx)), pred); if (!t) return false; const r = sendFieldToGrave(ctx, my(ctx), getCardId(t), reason); return !!(r && r.ok); }
  function sendOpponentFieldFirst(ctx, pred, reason) { const t = first(field(ctx, opp(ctx)), pred); if (!t) return false; const r = sendFieldToGrave(ctx, opp(ctx), getCardId(t), reason); return !!(r && r.ok); }
  function canPlaceRlyeh(ctx) { return deck(ctx).some(c => getCardId(c) === '태평양 속 르뤼에'); }
  function placeRlyehFromDeck(ctx) { if (!canPlaceRlyeh(ctx)) return false; const r = ctx.move.placeFieldCard({ cardId: '태평양 속 르뤼에', controller: my(ctx), from: { controller: my(ctx), zone: ZONES.DECK }, reason: 'cthulhuPlaceRlyehByEffect', activate: false }); dispatch(ctx); return !!(r && r.ok); }

  function costSummonSelfFromHand(ctx, cardId) { if (!hasFieldSpace(ctx, my(ctx)) || !hand(ctx).some(c => getCardId(c) === cardId)) return { ok: false, error: '패에서 소환할 수 없습니다.' }; const r = summonFromZone(ctx, cardId, ZONES.HAND, 'cthulhuCostSummonSelf'); if (r && r.ok) dispatch(ctx); return r && r.ok ? { ok: true } : { ok: false, error: (r && r.error) || '소환 실패' }; }
  function costBanishSelfFromGrave(ctx, cardId) { if (!grave(ctx).some(c => getCardId(c) === cardId)) return { ok: false, error: '묘지에 이 카드가 없습니다.' }; const r = moveById(ctx, ZONES.GRAVE, ZONES.EXILE, cardId, my(ctx), my(ctx), 'cthulhuCostBanishSelf'); if (r && r.ok) dispatch(ctx); return r && r.ok ? { ok: true } : { ok: false, error: (r && r.error) || '제외 실패' }; }

  const effects = [];
  function add(def) { effects.push(Object.assign({ theme: '올드원' }, def)); }

  // Great Old One — 크툴루
  add({ id: 'cthulhu-goo-cthulhu-1-cost-summon-place-rlyeh', cardId: '그레이트 올드 원-크툴루', effectNo: 1, type: EFFECT_TYPES.ACTIVATION, zones: [ZONES.HAND], timing: TIMING.MY_DEPLOY, tags: [TAGS.COST_SUMMON, TAGS.FIELD_ZONE_EFFECT, 'greatOldOneEffect'], text: '이 카드를 패에서 소환하고 발동할 수 있다. 덱에서 태평양 속 르뤼에를 필드 존에 놓는다.', condition: ctx => hasFieldSpace(ctx, my(ctx)) && hand(ctx).some(c => getCardId(c) === '그레이트 올드 원-크툴루'), canResolve: canPlaceRlyeh, cost: ctx => costSummonSelfFromHand(ctx, '그레이트 올드 원-크툴루'), resolve: placeRlyehFromDeck });
  add({ id: 'cthulhu-goo-cthulhu-2-cost-field-send-own-field', cardId: '그레이트 올드 원-크툴루', effectNo: 2, type: EFFECT_TYPES.ACTIVATION, zones: [ZONES.FIELD], timing: TIMING.MY_DEPLOY, tags: [TAGS.COST_SEND_TO_GRAVE, 'greatOldOneEffect'], text: '필드의 카드 1장을 묘지로 보내고 발동할 수 있다. 자신 필드의 카드 1장을 묘지로 보낸다.', canResolve: ctx => field(ctx, my(ctx)).length > 0 && (field(ctx, my(ctx)).length + field(ctx, opp(ctx)).length > 0), cost(ctx) { const t = first(field(ctx, my(ctx))) || first(field(ctx, opp(ctx))); if (!t) return { ok: false }; const owner = field(ctx, my(ctx)).indexOf(t) >= 0 ? my(ctx) : opp(ctx); return sendFieldToGrave(ctx, owner, getCardId(t), 'cthulhu2Cost'); }, resolve(ctx) { const ok = sendOwnFieldFirst(ctx, null, 'cthulhu2Penalty'); dispatch(ctx); return ok; } });
  add({ id: 'cthulhu-goo-cthulhu-3-grave-search-goo', cardId: '그레이트 올드 원-크툴루', effectNo: 3, type: EFFECT_TYPES.TRIGGER, zones: [ZONES.GRAVE], events: [EVENTS.SENT_TO_GRAVE], optional: true, timing: TIMING.ON_SENT_TO_GRAVE, tags: [TAGS.DECK_SEARCH, 'greatOldOneEffect'], text: '묘지로 보내졌을 경우 덱에서 그레이트 올드 원 몬스터 1장을 패에 넣는다.', condition: ctx => ctx.event && ctx.event.cardId === '그레이트 올드 원-크툴루', canResolve: ctx => deck(ctx).some(isGOO), resolve(ctx) { const ok = searchToHand(ctx, isGOO, '크툴루③'); dispatch(ctx); return ok; } });

  // 르뤼에
  add({ id: 'cthulhu-rlyeh-1-field-zone-summon-goo-from-grave', cardId: '태평양 속 르뤼에', effectNo: 1, type: EFFECT_TYPES.ACTIVATION, zones: [ZONES.FIELD_ZONE], timing: TIMING.MY_DEPLOY, tags: [TAGS.FIELD_ZONE_EFFECT, TAGS.GRAVE_SUMMON], text: '자신 전개 단계에 묘지의 그레이트 올드 원 몬스터 1장을 소환한다.', canResolve: ctx => hasFieldSpace(ctx, my(ctx)) && grave(ctx).some(isGOO), resolve(ctx) { const t = first(grave(ctx), isGOO); const ok = t && summonFromZone(ctx, getCardId(t), ZONES.GRAVE, 'rlyehSummonGOO'); dispatch(ctx); return !!(ok && ok.ok); } });
  add({ id: 'cthulhu-rlyeh-2-field-zone-recover-goo-banish-elder', cardId: '태평양 속 르뤼에', effectNo: 2, type: EFFECT_TYPES.ACTIVATION, zones: [ZONES.FIELD_ZONE], timing: TIMING.MY_DEPLOY, tags: [TAGS.FIELD_ZONE_EFFECT, TAGS.COST_BANISH], text: '묘지의 GOO 1장을 패에 넣고 발동할 수 있다. 덱의 엘더 갓 카드 1장을 제외한다.', canResolve: ctx => grave(ctx).some(isGOO) && deck(ctx).some(isElder), cost(ctx) { const t = first(grave(ctx), isGOO); if (!t) return { ok: false }; moveById(ctx, ZONES.GRAVE, ZONES.HAND, getCardId(t), my(ctx), my(ctx), 'rlyeh2CostRecover'); dispatch(ctx); return { ok: true }; }, resolve(ctx) { const ok = banishFromDeck(ctx, isElder, '르뤼에②'); dispatch(ctx); return ok; } });
  add({ id: 'cthulhu-rlyeh-3-processing-negate-goo', cardId: '태평양 속 르뤼에', effectNo: 3, type: EFFECT_TYPES.PROCESSING_NEGATE || 'processingNegate', zones: [ZONES.FIELD_ZONE], timing: TIMING.NONE, isActivated: false, optional: true, negateTags: ['greatOldOneEffect'], tags: [TAGS.PROCESSING_NEGATE, TAGS.NEGATE_EFFECT], text: '자신이 발동한 그레이트 올드 원 몬스터의 효과 처리 시 그 효과를 무효로 할 수 있다.', processingNegate: { negateTags: ['greatOldOneEffect'], ownEffectsOnly: true } });

  // 그레이트 올드 원 — 크투가/크아이가/과타노차
  add({ id: 'cthulhu-goo-cthuga-1-summon-cost-field-zone-send', cardId: '그레이트 올드 원-크투가', effectNo: 1, type: EFFECT_TYPES.ACTIVATION, zones: [ZONES.HAND], timing: TIMING.MY_DEPLOY, tags: [TAGS.COST_SUMMON, 'greatOldOneEffect'], text: '이 카드를 패에서 소환하고 발동할 수 있다. 필드 존의 카드 1장을 묘지로 보낸다.', canResolve: ctx => hasFieldSpace(ctx, my(ctx)) && hand(ctx).some(c => getCardId(c) === '그레이트 올드 원-크투가') && (zoneAccess.getFieldZoneCard(ctx.gameState, my(ctx)) || zoneAccess.getFieldZoneCard(ctx.gameState, opp(ctx))), cost: ctx => costSummonSelfFromHand(ctx, '그레이트 올드 원-크투가'), resolve(ctx) { const own = zoneAccess.getFieldZoneCard(ctx.gameState, my(ctx)); const owner = own ? my(ctx) : opp(ctx); const card = own || zoneAccess.getFieldZoneCard(ctx.gameState, opp(ctx)); if (!card) return false; const r = ctx.move.removeFieldCard({ controller: owner, to: { controller: owner, zone: ZONES.GRAVE }, reason: 'cthuga1' }); dispatch(ctx); return !!(r && r.ok); } });
  add({ id: 'cthulhu-goo-cthuga-3-grave-banish-up-to-2', cardId: '그레이트 올드 원-크투가', effectNo: 3, type: EFFECT_TYPES.TRIGGER, zones: [ZONES.GRAVE], events: [EVENTS.SENT_TO_GRAVE], optional: true, timing: TIMING.ON_SENT_TO_GRAVE, tags: [TAGS.COST_BANISH, 'greatOldOneEffect'], text: '묘지로 보내졌을 경우 서로 묘지의 카드 2장까지 제외한다.', condition: ctx => ctx.event && ctx.event.cardId === '그레이트 올드 원-크투가', canResolve: ctx => grave(ctx).length + zoneArray(ctx, opp(ctx), ZONES.GRAVE).length > 0, resolve(ctx) { let n = 0; while (n < 2 && grave(ctx).length) { const c = grave(ctx)[0]; const r = ctx.move.banishCard({ cardId: getCardId(c), controller: my(ctx), from: { controller: my(ctx), zone: ZONES.GRAVE, index: 0 }, reason: 'cthuga3BanishOwnGrave' }); if (!r || r.ok === false) break; n += 1; } while (n < 2 && zoneArray(ctx, opp(ctx), ZONES.GRAVE).length) { const c = zoneArray(ctx, opp(ctx), ZONES.GRAVE)[0]; const r = ctx.move.banishCard({ cardId: getCardId(c), controller: opp(ctx), from: { controller: opp(ctx), zone: ZONES.GRAVE, index: 0 }, reason: 'cthuga3BanishOpponentGrave' }); if (!r || r.ok === false) break; n += 1; } dispatch(ctx); return n > 0; } });
  add({ id: 'cthulhu-goo-khaiga-1-quick-cost-summon-discard', cardId: '그레이트 올드 원-크아이가', effectNo: 1, type: EFFECT_TYPES.QUICK, zones: [ZONES.HAND], timing: TIMING.EITHER_TURN, tags: [TAGS.COST_SUMMON, TAGS.DISCARD_HAND, 'greatOldOneEffect'], text: '자신/상대 턴에 이 카드를 소환하고 발동할 수 있다. 자신 패를 1장 버린다.', canResolve: ctx => hasFieldSpace(ctx, my(ctx)) && hand(ctx).some(c => getCardId(c) === '그레이트 올드 원-크아이가') && hand(ctx).length >= 2, cost: ctx => costSummonSelfFromHand(ctx, '그레이트 올드 원-크아이가'), resolve(ctx) { const ok = discardOne(ctx, '크아이가①'); dispatch(ctx); return ok; } });
  add({ id: 'cthulhu-goo-khaiga-2-quick-send-op-field-discard', cardId: '그레이트 올드 원-크아이가', effectNo: 2, type: EFFECT_TYPES.QUICK, zones: [ZONES.FIELD], timing: TIMING.EITHER_TURN, tags: [TAGS.DISCARD_HAND, 'greatOldOneEffect'], text: '자신/상대 턴에 상대 필드의 카드 1장을 묘지로 보내고 발동할 수 있다. 자신 패를 1장 버린다.', canResolve: ctx => field(ctx, opp(ctx)).length > 0 && hand(ctx).length > 0, cost(ctx) { const ok = sendOpponentFieldFirst(ctx, null, '크아이가② cost'); return ok ? { ok: true } : { ok: false }; }, resolve(ctx) { const ok = discardOne(ctx, '크아이가②'); dispatch(ctx); return ok; } });
  add({ id: 'cthulhu-goo-khaiga-4-grave-banish-elder-from-deck', cardId: '그레이트 올드 원-크아이가', effectNo: 4, type: EFFECT_TYPES.ACTIVATION, zones: [ZONES.GRAVE], timing: TIMING.MY_DEPLOY, tags: [TAGS.COST_BANISH], text: '묘지의 이 카드를 제외하고 덱에서 엘더 갓 몬스터 1장을 제외한다.', canResolve: ctx => grave(ctx).some(c => getCardId(c) === '그레이트 올드 원-크아이가') && deck(ctx).some(isElder), cost: ctx => costBanishSelfFromGrave(ctx, '그레이트 올드 원-크아이가'), resolve(ctx) { const ok = banishFromDeck(ctx, isElder, '크아이가④'); dispatch(ctx); return ok; } });
  add({ id: 'cthulhu-goo-ghatanothoa-1-cost-goo-summon-draw', cardId: '그레이트 올드 원-과타노차', effectNo: 1, type: EFFECT_TYPES.ACTIVATION, zones: [ZONES.HAND], timing: TIMING.MY_DEPLOY, tags: [TAGS.COST_SEND_TO_GRAVE, TAGS.COST_SUMMON, TAGS.DRAW, 'greatOldOneEffect'], text: '자신 필드의 GOO 1장을 묘지로 보내고 이 카드를 소환한다. 그 후 1장 드로우할 수 있다.', canResolve: ctx => hasFieldSpace(ctx, my(ctx)) && hand(ctx).some(c => getCardId(c) === '그레이트 올드 원-과타노차') && field(ctx, my(ctx)).some(isGOO), cost(ctx) { const ok = sendOwnFieldFirst(ctx, isGOO, '과타노차① cost'); if (!ok) return { ok: false }; return costSummonSelfFromHand(ctx, '그레이트 올드 원-과타노차'); }, resolve(ctx) { if (typeof drawOne === 'function') drawOne(); dispatch(ctx); return true; } });
  add({ id: 'cthulhu-goo-ghatanothoa-2-field-cost-summon-goo', cardId: '그레이트 올드 원-과타노차', effectNo: 2, type: EFFECT_TYPES.ACTIVATION, zones: [ZONES.FIELD], timing: TIMING.MY_DEPLOY, tags: [TAGS.COST_SEND_TO_GRAVE, TAGS.HAND_SUMMON, 'greatOldOneEffect'], text: '필드의 이 카드와 상대 패/필드 카드 1장을 묘지로 보내고 패에서 GOO 1장을 소환한다.', canResolve: ctx => field(ctx, my(ctx)).some(c => getCardId(c) === '그레이트 올드 원-과타노차') && hand(ctx).some(isGOO) && hasFieldSpace(ctx, my(ctx)) && (field(ctx, opp(ctx)).length > 0 || zoneArray(ctx, opp(ctx), ZONES.HAND).length > 0), cost(ctx) { sendOwnFieldFirst(ctx, c => getCardId(c) === '그레이트 올드 원-과타노차', '과타노차② cost self'); if (field(ctx, opp(ctx)).length) sendOpponentFieldFirst(ctx, null, '과타노차② cost opponent'); return { ok: true }; }, resolve(ctx) { const t = first(hand(ctx), isGOO); const r = t && summonFromZone(ctx, getCardId(t), ZONES.HAND, '과타노차② summon'); dispatch(ctx); return !!(r && r.ok); } });

  // Elder God
  add({ id: 'cthulhu-elder-nodens-1-grave-exile-summon-self-send-goo', cardId: '엘더 갓-노덴스', effectNo: 1, type: EFFECT_TYPES.TRIGGER, zones: [ZONES.GRAVE, ZONES.EXILE], events: [EVENTS.SENT_TO_GRAVE, EVENTS.EXILED], optional: true, timing: TIMING.ON_SENT_TO_GRAVE, tags: [TAGS.GRAVE_SUMMON, TAGS.EXILE_SUMMON], text: '묘지/제외로 보내졌을 경우 이 카드를 소환하고 자신 필드의 GOO 1장 이상을 묘지로 보낸다.', condition: ctx => ctx.event && ctx.event.cardId === '엘더 갓-노덴스', canResolve: ctx => hasFieldSpace(ctx, my(ctx)) && (grave(ctx).some(c => getCardId(c) === '엘더 갓-노덴스') || exile(ctx).some(c => getCardId(c) === '엘더 갓-노덴스')), resolve(ctx) { const from = grave(ctx).some(c => getCardId(c) === '엘더 갓-노덴스') ? ZONES.GRAVE : ZONES.EXILE; const r = summonFromZone(ctx, '엘더 갓-노덴스', from, 'nodens1'); sendOwnFieldFirst(ctx, isGOO, '노덴스① penalty'); dispatch(ctx); return !!(r && r.ok); } });
  add({ id: 'cthulhu-elder-nodens-2-banish-goo-send-goo-deck-grave', cardId: '엘더 갓-노덴스', effectNo: 2, type: EFFECT_TYPES.QUICK, zones: [ZONES.HAND, ZONES.FIELD], timing: TIMING.EITHER_TURN, tags: [TAGS.COST_BANISH], text: '묘지의 GOO 1장을 제외하고 덱에서 GOO 1장을 묘지로 보낸다.', canResolve: ctx => grave(ctx).some(isGOO) && deck(ctx).some(isGOO), cost(ctx) { const t = first(grave(ctx), isGOO); if (!t) return { ok: false }; moveById(ctx, ZONES.GRAVE, ZONES.EXILE, getCardId(t), my(ctx), my(ctx), '노덴스② cost'); dispatch(ctx); return { ok: true }; }, resolve(ctx) { const ok = sendDeckToGrave(ctx, isGOO, '노덴스②'); dispatch(ctx); return ok; } });
  add({ id: 'cthulhu-elder-cthanit-1-exiled-summon-draw-both', cardId: '엘더 갓-크타니트', effectNo: 1, type: EFFECT_TYPES.TRIGGER, zones: [ZONES.EXILE], events: [EVENTS.EXILED], optional: true, timing: TIMING.NONE, tags: [TAGS.EXILE_SUMMON, TAGS.DRAW], text: '제외되었을 경우 이 카드를 소환하고 서로 1장 드로우한다.', condition: ctx => ctx.event && ctx.event.cardId === '엘더 갓-크타니트', canResolve: ctx => hasFieldSpace(ctx, my(ctx)) && exile(ctx).some(c => getCardId(c) === '엘더 갓-크타니트'), resolve(ctx) { const r = summonFromZone(ctx, '엘더 갓-크타니트', ZONES.EXILE, 'cthanit1'); if (typeof drawOne === 'function') drawOne(); dispatch(ctx); return !!(r && r.ok); } });
  add({ id: 'cthulhu-elder-cthanit-2-on-summon-op-discard-draw', cardId: '엘더 갓-크타니트', effectNo: 2, type: EFFECT_TYPES.TRIGGER, zones: [ZONES.FIELD], events: [EVENTS.SUMMON], optional: true, timing: TIMING.ON_SUMMON, tags: [TAGS.DISCARD_HAND, TAGS.DRAW], text: '소환했을 경우 상대가 패 1장을 버리고 자신은 1장 드로우한다.', condition: ctx => ctx.event && ctx.event.cardId === '엘더 갓-크타니트', canResolve: () => true, resolve(ctx) { if (typeof drawOne === 'function') drawOne(); dispatch(ctx); return true; } });
  add({ id: 'cthulhu-elder-hypnos-2-continuous-target-protect', cardId: '엘더 갓-히프노스', effectNo: 2, type: EFFECT_TYPES.CONTINUOUS, zones: [ZONES.FIELD], timing: TIMING.NONE, text: '상대는 자신 필드의 다른 카드를 효과의 대상으로 할 수 없다.', continuousRule: { targetProtection: { protectOtherAlliedCards: true } } });
  add({ id: 'cthulhu-elder-hypnos-3-grave-monster-summon', cardId: '엘더 갓-히프노스', effectNo: 3, type: EFFECT_TYPES.ACTIVATION, zones: [ZONES.FIELD], timing: TIMING.MY_DEPLOY, tags: [TAGS.GRAVE_SUMMON], text: '자신 공격 단계에 묘지에서 몬스터 1장을 소환한다.', canResolve: ctx => hasFieldSpace(ctx, my(ctx)) && grave(ctx).some(isMonster), resolve(ctx) { const t = first(grave(ctx), isMonster); const r = t && summonFromZone(ctx, getCardId(t), ZONES.GRAVE, 'hypnos3'); dispatch(ctx); return !!(r && r.ok); } });

  // Outer God — key deck only
  add({ id: 'cthulhu-outer-nyarlathotep-1-procedure-cost-key-summon', cardId: '아우터 갓 니알라토텝', effectNo: 1, type: EFFECT_TYPES.PROCEDURE, zones: [ZONES.KEY_DECK], timing: TIMING.MY_DEPLOY, summonProcedure: true, label: '아우터 갓 니알라토텝 소환', tags: [TAGS.KEY_DECK_SUMMON, TAGS.COST_SEND_TO_GRAVE], text: '상대 필드 카드 1장과 자신 필드 GOO/엘더 갓 2장을 묘지로 보내고 키 카드 덱에서 소환한다.', canResolve: ctx => hasFieldSpace(ctx, my(ctx)) && keyDeck(ctx).some(c => getCardId(c) === '아우터 갓 니알라토텝') && field(ctx, opp(ctx)).length > 0 && field(ctx, my(ctx)).filter(c => isGOO(c) || isElder(c)).length >= 2, resolve(ctx) { sendOpponentFieldFirst(ctx, null, '니알라토텝 cost opponent'); let n = 0; field(ctx, my(ctx)).slice().forEach(c => { if (n < 2 && (isGOO(c) || isElder(c))) { sendOwnFieldFirst(ctx, x => x === c, '니알라토텝 cost own'); n += 1; } }); const r = summonFromZone(ctx, '아우터 갓 니알라토텝', ZONES.KEY_DECK, 'nyarlathotepProcedure'); dispatch(ctx); return !!(r && r.ok); } });
  add({ id: 'cthulhu-outer-nyarlathotep-2-on-summon-copy-negate', cardId: '아우터 갓 니알라토텝', effectNo: 2, type: EFFECT_TYPES.TRIGGER, zones: [ZONES.FIELD], events: [EVENTS.SUMMON], optional: true, timing: TIMING.ON_SUMMON, tags: [TAGS.NEGATE_EFFECT], text: '소환했을 경우 상대 몬스터 1장의 효과를 턴 종료시까지 무효로 하고 그 공격력을 얻는다.', condition: ctx => ctx.event && ctx.event.cardId === '아우터 갓 니알라토텝', canResolve: ctx => field(ctx, opp(ctx)).length > 0, resolve(ctx) { const target = first(field(ctx, opp(ctx))); const self = first(field(ctx, my(ctx)), c => getCardId(c) === '아우터 갓 니알라토텝'); if (target && self) { self.copiedFrom = getCardId(target); self.atk = getCardDef(target)?.atk || self.atk || 0; target.negatedUntilTurnEnd = true; } dispatch(ctx); return !!target; } });
  add({ id: 'cthulhu-outer-azathoth-1-continuous-immunity', cardId: '아우터 갓-아자토스', effectNo: 1, type: EFFECT_TYPES.CONTINUOUS, zones: [ZONES.FIELD], timing: TIMING.NONE, text: '이 카드는 다른 카드의 효과를 받지 않으며 묘지로 보내지지 않는다.', continuousRule: { effectImmunity: { allEffects: true }, cannotBeSentToGrave: true } });
  add({ id: 'cthulhu-outer-azathoth-3-quick-negate-banish-fields', cardId: '아우터 갓-아자토스', effectNo: 3, type: EFFECT_TYPES.QUICK, zones: [ZONES.FIELD], timing: TIMING.EITHER_TURN, tags: [TAGS.NEGATE_EFFECT], text: '필드 카드 3장까지 효과를 무효로 하고 서로 필드의 카드를 같은 수만큼 제외한다.', canResolve: ctx => field(ctx, my(ctx)).length + field(ctx, opp(ctx)).length > 0, resolve(ctx) { let count = 0; while (count < 2 && field(ctx, my(ctx)).length && field(ctx, opp(ctx)).length) { const a = field(ctx, my(ctx))[0]; moveById(ctx, ZONES.FIELD, ZONES.EXILE, getCardId(a), my(ctx), my(ctx), 'azathoth3'); const b = field(ctx, opp(ctx))[0]; moveById(ctx, ZONES.FIELD, ZONES.EXILE, getCardId(b), opp(ctx), opp(ctx), 'azathoth3'); count += 1; } dispatch(ctx); return true; } });
  add({ id: 'cthulhu-outer-shub-1-goo-summon-key-trigger', cardId: '아우터 갓 슈브 니구라스', effectNo: 1, type: EFFECT_TYPES.TRIGGER, zones: [ZONES.KEY_DECK], events: [EVENTS.SUMMON], optional: true, timing: TIMING.ON_SUMMON, tags: [TAGS.KEY_DECK_SUMMON], text: '자신 필드에 GOO 몬스터가 소환됐을 경우 이 카드를 소환하고 덱에서 GOO 1장을 묘지로 보낸다.', condition: ctx => ctx.event && isGOO(ctx.event.cardId), canResolve: ctx => hasFieldSpace(ctx, my(ctx)) && keyDeck(ctx).some(c => getCardId(c) === '아우터 갓 슈브 니구라스') && deck(ctx).some(isGOO), resolve(ctx) { const r = summonFromZone(ctx, '아우터 갓 슈브 니구라스', ZONES.KEY_DECK, 'shub1'); sendDeckToGrave(ctx, isGOO, '슈브①'); dispatch(ctx); return !!(r && r.ok); } });
  add({ id: 'cthulhu-outer-shub-2-response-banish-elder-negate', cardId: '아우터 갓 슈브 니구라스', effectNo: 2, type: EFFECT_TYPES.QUICK, zones: [ZONES.FIELD], timing: TIMING.EITHER_TURN, tags: [TAGS.COST_BANISH, TAGS.NEGATE_EFFECT], text: '상대가 효과를 발동했을 때 덱에서 엘더 갓 몬스터 1장을 제외하고 그 효과를 무효로 한다.', canResolve: ctx => deck(ctx).some(isElder), cost(ctx) { const ok = banishFromDeck(ctx, isElder, '슈브② cost'); dispatch(ctx); return { ok }; }, resolve(ctx) { if (ctx.chainLink) ctx.chainLink.negated = true; dispatch(ctx); return true; } });
  add({ id: 'cthulhu-outer-shub-3-continuous-immunity-no-attack-target', cardId: '아우터 갓 슈브 니구라스', effectNo: 3, type: EFFECT_TYPES.CONTINUOUS, zones: [ZONES.FIELD], timing: TIMING.NONE, text: '이 카드는 상대 카드 효과를 받지 않으며 공격 대상이 되지 않는다.', continuousRule: { effectImmunity: { opponentEffects: true }, cannotBeAttackTarget: true } });

  // Magic
  add({ id: 'cthulhu-ruin-1-banish-elder-summon-goo', cardId: '올드_원의 멸망', effectNo: 1, type: EFFECT_TYPES.ACTIVATION, cardActivationCost: true, zones: [ZONES.HAND], timing: TIMING.MY_DEPLOY, tags: [TAGS.COST_BANISH, TAGS.DECK_SUMMON, TAGS.GRAVE_SUMMON], text: '덱에서 엘더 갓 몬스터를 제외하고 덱/묘지에서 GOO 1장을 소환한다.', canResolve: ctx => hasFieldSpace(ctx, my(ctx)) && deck(ctx).some(isElder) && (deck(ctx).some(isGOO) || grave(ctx).some(isGOO)), cost(ctx) { const ok = banishFromDeck(ctx, isElder, '멸망① cost'); dispatch(ctx); return { ok }; }, resolve(ctx) { const t = first(deck(ctx), isGOO); let r; if (t) r = summonFromZone(ctx, getCardId(t), ZONES.DECK, 'ruin1'); else { const g = first(grave(ctx), isGOO); r = g && summonFromZone(ctx, getCardId(g), ZONES.GRAVE, 'ruin1'); } dispatch(ctx); return !!(r && r.ok); } });
  add({ id: 'cthulhu-ruin-2-grave-banish-search-old-one', cardId: '올드_원의 멸망', effectNo: 2, type: EFFECT_TYPES.QUICK, zones: [ZONES.GRAVE], timing: TIMING.EITHER_TURN, tags: [TAGS.COST_BANISH, TAGS.DECK_SEARCH], text: '상대 턴에 묘지의 이 카드를 제외하고 덱에서 올드원 카드 1장을 패에 넣는다.', canResolve: ctx => grave(ctx).some(c => getCardId(c) === '올드_원의 멸망') && deck(ctx).some(isOldOne), cost: ctx => costBanishSelfFromGrave(ctx, '올드_원의 멸망'), resolve(ctx) { const ok = searchToHand(ctx, isOldOne, '멸망②'); dispatch(ctx); return ok; } });

  const registered = registry.registerEffects(effects);
  registry.syncEffectIdsToCards();

  global.HB_CTHULHU_EFFECTS = Object.freeze({
    effects: registered,
    GOO_IDS,
    ELDER_IDS,
    OUTER_IDS,
    isGOO,
    isElder,
    isOuter,
    isOldOne,
    getCthulhuEffectIds: () => effects.map(e => e.id),
    getCthulhuCards: () => { const cards = getCardDatabase() || {}; return Object.keys(cards).filter(id => isOldOne(id) || GOO_IDS.includes(id) || ELDER_IDS.includes(id) || OUTER_IDS.includes(id)); },
    getCthulhuImplementationSpec: () => Object.freeze({
      theme: '올드원/크툴루',
      registeredEffectCount: effects.length,
      costSeparatedEffects: effects.filter(e => String(e.id).includes('cost') || (e.tags || []).indexOf(TAGS.COST_SEND_TO_GRAVE) !== -1 || (e.tags || []).indexOf(TAGS.COST_BANISH) !== -1).map(e => e.id),
      processingNegates: effects.filter(e => e.type === (EFFECT_TYPES.PROCESSING_NEGATE || 'processingNegate')).map(e => e.id),
      keyDeckProcedures: effects.filter(e => e.summonProcedure).map(e => e.id),
      notes: ['GOO의 소환하고 발동은 cost에서 소환한다.', '르뤼에 ③은 processingNegate로 등록한다.', '아우터 갓은 keyDeck procedure/trigger로만 나온다.', '처리 불가능하면 canResolve에서 발동 전 차단한다.'],
    }),
  });
})(typeof window !== 'undefined' ? window : globalThis);
