// HAND BATTLE — Theme Effects: Jibaeja / Jibaeryong
// 보정 단계: 지배자/지배룡 테마를 EffectDefinition 기반으로 이식한다.
// 핵심 원칙:
// - 처리 불가능한 서치/소환/드로우/버리기 효과는 canResolve에서 발동 전 차단한다.
// - 사원소의 지배자/지배룡 자체 소환은 procedure이며 체인을 만들지 않는다.
// - 지배룡 ①/②, 지배의 사슬 ①은 이벤트 기반 trigger다.
// - 사원소의 기적 추가 코스트는 신규 효과 resolve 전에 공통으로 처리한다.
(function initRulerEffectDefinitions(global) {
  'use strict';

  const rules = global.HB_RULES || {};
  const EFFECT_TYPES = rules.EFFECT_TYPES || Object.freeze({ ACTIVATION: 'activation', QUICK: 'quick', TRIGGER: 'trigger', CONTINUOUS: 'continuous', PROCEDURE: 'procedure' });
  const ZONES = rules.ZONES || Object.freeze({ DECK: 'deck', HAND: 'hand', PUBLIC_HAND: 'publicHand', FIELD: 'field', FIELD_ZONE: 'fieldZone', GRAVE: 'grave', EXILE: 'exile', KEY_DECK: 'keyDeck' });
  const EVENTS = rules.EVENTS || Object.freeze({ SUMMON: 'summon', SENT_TO_GRAVE: 'sentToGrave', DISCARDED: 'discarded', CARD_ACTIVATED: 'cardActivated' });
  const TIMING = rules.TIMING || Object.freeze({ MY_DEPLOY: 'myDeploy', EITHER_TURN: 'eitherTurn', ON_SUMMON: 'onSummon', ON_SENT_TO_GRAVE: 'onSentToGrave', NONE: 'none' });
  const TAGS = rules.EFFECT_TAGS || Object.freeze({ DECK_SEARCH: 'deckSearch', DECK_SUMMON: 'deckSummon', GRAVE_SUMMON: 'graveSummon', EXILE_SUMMON: 'exileSummon', COST_DISCARD: 'costDiscard', COST_BANISH: 'costBanish', COST_SEND_TO_GRAVE: 'costSendToGrave', DRAW: 'draw', DISCARD_HAND: 'discardHand', NEGATE_EFFECT: 'negateEffect' });

  const registry = global.HB_EFFECT_REGISTRY;
  const zoneAccess = global.HB_ZONE_ACCESS;
  if (!registry) throw new Error('[ruler-effects] HB_EFFECT_REGISTRY가 필요합니다.');
  if (!zoneAccess) throw new Error('[ruler-effects] HB_ZONE_ACCESS가 필요합니다.');

  const CONTROLLERS = zoneAccess.CONTROLLERS || Object.freeze({ ME: 'me', OPPONENT: 'opponent' });
  const RULER_IDS = Object.freeze(['수원소의 지배자', '화원소의 지배자', '전원소의 지배자', '풍원소의 지배자']);
  const DRAGON_IDS = Object.freeze(['수원소의 지배룡', '화원소의 지배룡', '전원소의 지배룡', '풍원소의 지배룡']);
  const KEY_IDS = Object.freeze(['사원소의 지배자', '사원소의 지배룡']);
  const ALL_IDS = Object.freeze([...RULER_IDS, ...DRAGON_IDS, ...KEY_IDS, '사원소의 기적', '지배의 사슬', '지배룡과 지배자']);

  function getDefaultGameState() { if (typeof G !== 'undefined') return G; return global.G || null; } // eslint-disable-line no-undef
  function getCardDatabase() { if (typeof CARDS !== 'undefined' && CARDS) return CARDS; return global.CARDS || null; } // eslint-disable-line no-undef
  function stateOf(ctxOrState) { return (ctxOrState && ctxOrState.gameState) || ctxOrState || getDefaultGameState(); }
  function normalizeController(controller) { return zoneAccess.normalizeController(controller || CONTROLLERS.ME); }
  function my(ctx) { return normalizeController(ctx && ctx.controller); }
  function opp(ctx) { return my(ctx) === CONTROLLERS.ME ? CONTROLLERS.OPPONENT : CONTROLLERS.ME; }
  function zoneArray(ctx, controller, zone) { return zoneAccess.getZoneArray(stateOf(ctx), normalizeController(controller || CONTROLLERS.ME), zone); }
  function field(ctx, controller) { return zoneArray(ctx, controller || my(ctx), ZONES.FIELD); }
  function hand(ctx, controller) { return zoneArray(ctx, controller || my(ctx), ZONES.HAND); }
  function publicHand(ctx, controller) { return zoneArray(ctx, controller || my(ctx), ZONES.PUBLIC_HAND); }
  function deck(ctx, controller) { return zoneArray(ctx, controller || my(ctx), ZONES.DECK); }
  function grave(ctx, controller) { return zoneArray(ctx, controller || my(ctx), ZONES.GRAVE); }
  function exile(ctx, controller) { return zoneArray(ctx, controller || my(ctx), ZONES.EXILE); }
  function getCardId(cardOrId) { if (!cardOrId) return ''; return typeof cardOrId === 'string' ? cardOrId : (cardOrId.id || cardOrId.cardId || ''); }
  function getCardDef(cardOrId) { const cards = getCardDatabase(); const id = getCardId(cardOrId); return cards && id ? cards[id] || null : null; }
  function cardObj(cardId) { const def = getCardDef(cardId) || {}; return { id: cardId, name: def.name || cardId, atk: def.atk || 0, atkBase: def.atk || 0 }; }
  function isMonster(cardOrId) { const def = getCardDef(cardOrId); return !!(def && def.cardType === 'monster'); }
  function isJibaejaCard(cardOrId) { return /지배자/.test(getCardId(cardOrId)) || getCardId(cardOrId) === '지배의 사슬'; }
  function isJibaeryongCard(cardOrId) { return /지배룡/.test(getCardId(cardOrId)) || getCardId(cardOrId) === '지배의 사슬'; }
  function isRulerMonster(cardOrId) { return RULER_IDS.includes(getCardId(cardOrId)) || getCardId(cardOrId) === '사원소의 지배자'; }
  function isDragonMonster(cardOrId) { return DRAGON_IDS.includes(getCardId(cardOrId)) || getCardId(cardOrId) === '사원소의 지배룡'; }
  function isJibaeMonster(cardOrId) { return isMonster(cardOrId) && (isRulerMonster(cardOrId) || isDragonMonster(cardOrId)); }
  function first(list, pred) { return (list || []).find(pred || (x => x)); }
  function firstOrSelected(ctx, list, pred) { const selected = getCardId((ctx && (ctx.selectedCard || ctx.selectedTarget || ctx.target)) || (ctx && ctx.selectedCardId)); if (selected) { const hit = (list || []).find(c => getCardId(c) === selected && (!pred || pred(c))); if (hit) return hit; } return first(list, pred); }
  function hasDeck(ctx, pred, n) { return deck(ctx).filter(pred || (() => true)).length >= (n || 1); }
  function hasFieldSpace(ctx, controller) { return global.HB_CARD_MOVE && global.HB_CARD_MOVE.hasFieldSpace ? global.HB_CARD_MOVE.hasFieldSpace(stateOf(ctx), controller || my(ctx)) : field(ctx, controller || my(ctx)).length < 5; }
  function canDraw(ctx, n) { return deck(ctx).length >= (n || 1); }
  function isDeployPhase(ctx) { const phase = (ctx && ctx.gameState && ctx.gameState.phase) || (typeof currentPhase !== 'undefined' ? currentPhase : null); return !phase || phase === 'deploy' || phase === '전개' || phase === 'main'; } // eslint-disable-line no-undef
  function isAttackPhase(ctx) { const phase = (ctx && ctx.gameState && ctx.gameState.phase) || (typeof currentPhase !== 'undefined' ? currentPhase : null); return phase === 'attack' || phase === '공격'; } // eslint-disable-line no-undef
  function isMyTurnFallback(ctx) { if (ctx && ctx.gameState && ctx.gameState.activeController) return ctx.gameState.activeController === my(ctx); if (typeof isMyTurn !== 'undefined') return !!isMyTurn; return true; } // eslint-disable-line no-undef
  function keyCardMonsterOnEitherField(ctx) { return field(ctx, my(ctx)).concat(field(ctx, opp(ctx))).some(c => { const def = getCardDef(c); return def && def.isKeyCard && def.cardType === 'monster'; }); }
  function noActiveChain() { return !(global.HB_CHAIN_ENGINE && global.HB_CHAIN_ENGINE.hasActiveChain && global.HB_CHAIN_ENGINE.hasActiveChain()); }
  function notifySafe(msg) { try { if (typeof notify === 'function') notify(msg); } catch (_) {} } // eslint-disable-line no-undef
  function logSafe(msg, type) { try { if (typeof log === 'function') log(msg, type || 'mine'); } catch (_) {} } // eslint-disable-line no-undef
  function sync() { try { if (typeof sendGameState === 'function') sendGameState(); } catch (_) {} try { if (typeof renderAll === 'function') renderAll(); } catch (_) {} } // eslint-disable-line no-undef
  function dispatchPending(ctx) { if (global.HB_EVENTS && typeof global.HB_EVENTS.dispatchEvents === 'function') global.HB_EVENTS.dispatchEvents(ctx.gameState); sync(); }
  function draw(ctx, n) { let count = 0; for (let i = 0; i < (n || 1); i += 1) { const d = deck(ctx); if (!d.length) break; hand(ctx).push(d.shift()); count += 1; } if (count) logSafe(`지배자/지배룡: ${count}장 드로우`, 'mine'); return { ok: count === (n || 1), count }; }
  function removeFrom(list, cardOrId) { const id = getCardId(cardOrId); const i = (list || []).findIndex(c => getCardId(c) === id); return i >= 0 ? list.splice(i, 1)[0] : null; }
  function moveAddToHand(ctx, card, fromZone, reason, reveal) { return ctx.move.addToHand({ cardId: getCardId(card), controller: my(ctx), from: { controller: my(ctx), zone: fromZone }, reason: reason || 'rulerAddToHand', reveal: !!reveal }); }
  function moveSummon(ctx, card, fromZone, reason) { if (!hasFieldSpace(ctx)) return { ok: false, error: '몬스터 존이 가득 찼습니다.' }; return ctx.move.summonCard({ cardId: getCardId(card), controller: my(ctx), from: { controller: my(ctx), zone: fromZone }, reason: reason || 'rulerSummon' }); }
  function moveSendToGrave(ctx, card, fromZone, reason, controller) { return ctx.move.sendToGrave({ cardId: getCardId(card), controller: controller || my(ctx), from: { controller: controller || my(ctx), zone: fromZone }, reason: reason || 'rulerSendToGrave' }); }
  function moveBanish(ctx, card, fromZone, reason, controller) { return ctx.move.banishCard({ cardId: getCardId(card), controller: controller || my(ctx), from: { controller: controller || my(ctx), zone: fromZone }, reason: reason || 'rulerBanish' }); }
  function discardFirst(ctx, pred, reason) { const target = firstOrSelected(ctx, hand(ctx), pred || (() => true)); if (!target) return { ok: false, error: '버릴 패 없음' }; const r = ctx.move.discardCard({ cardId: getCardId(target), controller: my(ctx), reason: reason || 'rulerDiscard' }); return r; }
  function discardSelfFromHand(ctx, cardId) { return ctx.move.discardCard({ cardId, controller: my(ctx), reason: `${cardId}CostDiscardSelf` }); }
  function searchToHand(ctx, pred, reason, reveal) { const target = firstOrSelected(ctx, deck(ctx), pred); if (!target) return { ok: false, error: '서치 대상 없음' }; return moveAddToHand(ctx, target, ZONES.DECK, reason, reveal); }
  function summonFromDeck(ctx, pred, reason) { const target = firstOrSelected(ctx, deck(ctx), pred); if (!target) return { ok: false, error: '소환 대상 없음' }; return moveSummon(ctx, target, ZONES.DECK, reason); }
  function summonFromHandOrGrave(ctx, pred, reason) { const h = firstOrSelected(ctx, hand(ctx), pred); if (h) return moveSummon(ctx, h, ZONES.HAND, reason); const g = firstOrSelected(ctx, grave(ctx), pred); if (g) return moveSummon(ctx, g, ZONES.GRAVE, reason); return { ok: false, error: '패/묘지에 대상 없음' }; }
  function graveExile(ctx, pred) { return grave(ctx).concat(exile(ctx)).filter(pred || (() => true)); }
  function summonFromGraveExile(ctx, pred, reason) { const g = firstOrSelected(ctx, grave(ctx), pred); if (g) return moveSummon(ctx, g, ZONES.GRAVE, reason); const e = firstOrSelected(ctx, exile(ctx), pred); if (e) return moveSummon(ctx, e, ZONES.EXILE, reason); return { ok: false, error: '묘지/제외 대상 없음' }; }
  function sendDeckToGrave(ctx, pred, reason) { const target = firstOrSelected(ctx, deck(ctx), pred); if (!target) return { ok: false, error: '덱 대상 없음' }; return moveSendToGrave(ctx, target, ZONES.DECK, reason); }
  function sameNameCountInFieldGraveExile(ctx, pred) { const seen = new Set(); field(ctx).concat(grave(ctx), exile(ctx)).forEach(c => { if (pred(c)) seen.add(getCardId(c)); }); return seen.size; }
  function uniqueMaterials(ctx, pred) { const map = new Map(); field(ctx).concat(grave(ctx), exile(ctx)).forEach(c => { if (pred(c) && !map.has(getCardId(c))) map.set(getCardId(c), c); }); return Array.from(map.values()); }
  function removeMaterialById(ctx, id, pred) { const zones = [ZONES.FIELD, ZONES.GRAVE, ZONES.EXILE]; for (const z of zones) { const arr = zoneArray(ctx, my(ctx), z); const hit = arr.find(c => getCardId(c) === id && pred(c)); if (hit) return moveBanish(ctx, hit, z, 'rulerProcedureMaterial'); } return { ok: false, error: `${id} 소재 없음` }; }
  function applyMiracleTax(ctx, kind) { const st = stateOf(ctx); if (!st || !st.rulerMiracleActive) return { ok: true }; if (st.rulerMiracleType && kind && st.rulerMiracleType !== kind) return { ok: true }; return discardFirst(ctx, null, 'rulerMiracleTax'); }
  function selectedIds(ctx) { return (ctx && (ctx.selectedCardIds || ctx.materialIds || ctx.materials)) || []; }
  function chooseTwo(ctx, list) { const ids = selectedIds(ctx).map(getCardId); const picked = ids.length ? ids.map(id => list.find(c => getCardId(c) === id)).filter(Boolean) : list.slice(0, 2); return picked.slice(0, 2); }
  function optionalDiscardLoop(ctx, label) { let count = 0; while (hand(ctx).length && count < 20) { // 테스트/AI 기본값: 명시 선택이 없으면 더 버리지 않는다.
      const ids = selectedIds(ctx).map(getCardId);
      if (!ids.length) break;
      const target = hand(ctx).find(c => ids.includes(getCardId(c)));
      if (!target) break;
      const r = discardFirst(ctx, c => getCardId(c) === getCardId(target), label || 'rulerOptionalDiscard');
      if (!r.ok) break;
      count += 1;
    }
    return { ok: true, count };
  }

  function canHandDiscardQuick(ctx, cardId) { return hand(ctx).some(c => getCardId(c) === cardId) && (isMyTurnFallback(ctx) || keyCardMonsterOnEitherField(ctx)); }
  function handDiscardCost(cardId, kind) { return function cost(ctx) { const tax = applyMiracleTax(ctx, kind); if (!tax.ok) return tax; return discardSelfFromHand(ctx, cardId); }; }
  function afterDrawOptional(ctx) { if (canDraw(ctx, 1)) draw(ctx, 1); }
  function eventCardIs(ctx, id) { const e = ctx.event || {}; return getCardId(e.cardId || e.card) === id; }
  function eventFromNotHand(ctx) { const e = ctx.event || {}; const fromZone = (e.from && e.from.zone) || e.sourceZone || (e.eventData && e.eventData.sourceZone); return fromZone && fromZone !== ZONES.HAND; }
  function opponentFieldCards(ctx) { return field(ctx, opp(ctx)).concat(zoneAccess.getFieldZoneCard(stateOf(ctx), opp(ctx)) ? [zoneAccess.getFieldZoneCard(stateOf(ctx), opp(ctx))] : []); }
  function negateFieldCard(card) { if (!card) return false; card.negatedUntilEnd = true; card.effectNegatedUntilEnd = true; return true; }
  function protectAttackPhase(ctx) { const st = stateOf(ctx); st.rulerAttackPhaseProtected = true; return true; }

  const effects = [];
  function add(effect) { effects.push(effect); return effect; }
  function mk(base) { return Object.assign({ theme: '지배자', optional: true }, base); }

  // ── 기본 지배자 4종 ─────────────────────────────
  add(mk({ id: 'ruler-water-1-hand-discard-search', cardId: '수원소의 지배자', effectNo: 1, type: EFFECT_TYPES.QUICK, zones: [ZONES.HAND], timing: TIMING.EITHER_TURN, tags: [TAGS.COST_DISCARD, TAGS.DECK_SEARCH], oncePerTurn: { key: '수원소의 지배자_1', limit: 1 }, text: '패의 이 카드를 버리고 덱에서 지배자 몬스터 1장을 패에 넣는다. 그 후 1장 드로우할 수 있다.', condition: ctx => canHandDiscardQuick(ctx, '수원소의 지배자'), canResolve: ctx => hasDeck(ctx, isRulerMonster), cost: handDiscardCost('수원소의 지배자', 'jibaeja'), resolve(ctx) { const r = searchToHand(ctx, c => isRulerMonster(c), 'rulerWater1Search', true); afterDrawOptional(ctx); dispatchPending(ctx); return r; } }));
  add(mk({ id: 'ruler-fire-1-hand-discard-deck-summon', cardId: '화원소의 지배자', effectNo: 1, type: EFFECT_TYPES.QUICK, zones: [ZONES.HAND], timing: TIMING.EITHER_TURN, tags: [TAGS.COST_DISCARD, TAGS.DECK_SUMMON], oncePerTurn: { key: '화원소의 지배자_1', limit: 1 }, text: '패의 이 카드를 버리고 덱에서 지배자 몬스터 1장을 소환한다. 그 후 1장 드로우할 수 있다.', condition: ctx => canHandDiscardQuick(ctx, '화원소의 지배자'), canResolve: ctx => hasFieldSpace(ctx) && hasDeck(ctx, isRulerMonster), cost: handDiscardCost('화원소의 지배자', 'jibaeja'), resolve(ctx) { const r = summonFromDeck(ctx, c => isRulerMonster(c), 'rulerFire1Summon'); afterDrawOptional(ctx); dispatchPending(ctx); return r; } }));
  add(mk({ id: 'ruler-electric-1-hand-discard-summon-other', cardId: '전원소의 지배자', effectNo: 1, type: EFFECT_TYPES.QUICK, zones: [ZONES.HAND], timing: TIMING.EITHER_TURN, tags: [TAGS.COST_DISCARD, TAGS.HAND_SUMMON || 'handSummon', TAGS.GRAVE_SUMMON], oncePerTurn: { key: '전원소의 지배자_1', limit: 1 }, text: '패의 이 카드를 버리고 패/묘지의 다른 지배자 몬스터 1장을 소환한다. 그 후 1장 드로우할 수 있다.', condition: ctx => canHandDiscardQuick(ctx, '전원소의 지배자'), canResolve: ctx => hasFieldSpace(ctx) && hand(ctx).concat(grave(ctx)).some(c => isRulerMonster(c) && getCardId(c) !== '전원소의 지배자'), cost: handDiscardCost('전원소의 지배자', 'jibaeja'), resolve(ctx) { const r = summonFromHandOrGrave(ctx, c => isRulerMonster(c) && getCardId(c) !== '전원소의 지배자', 'rulerElectric1Summon'); afterDrawOptional(ctx); dispatchPending(ctx); return r; } }));
  add(mk({ id: 'ruler-wind-1-hand-discard-banish-op-grave', cardId: '풍원소의 지배자', effectNo: 1, type: EFFECT_TYPES.QUICK, zones: [ZONES.HAND], timing: TIMING.EITHER_TURN, tags: [TAGS.COST_DISCARD, TAGS.COST_BANISH, TAGS.DRAW], oncePerTurn: { key: '풍원소의 지배자_1', limit: 1 }, text: '패의 이 카드를 버리고 상대 묘지 카드 1장을 제외한다. 그 후 1장 드로우할 수 있다.', condition: ctx => canHandDiscardQuick(ctx, '풍원소의 지배자'), canResolve: ctx => grave(ctx, opp(ctx)).length > 0, cost: handDiscardCost('풍원소의 지배자', 'jibaeja'), resolve(ctx) { const target = firstOrSelected(ctx, grave(ctx, opp(ctx))); const r = target ? moveBanish(ctx, target, ZONES.GRAVE, 'rulerWind1BanishOpponentGrave', opp(ctx)) : { ok: false }; afterDrawOptional(ctx); dispatchPending(ctx); return r; } }));

  add(mk({ id: 'ruler-water-2-field-deck-summon', cardId: '수원소의 지배자', effectNo: 2, type: EFFECT_TYPES.ACTIVATION, zones: [ZONES.FIELD], timing: TIMING.MY_DEPLOY, tags: [TAGS.DECK_SUMMON], oncePerTurn: { key: '수원소의 지배자_2', limit: 1 }, condition: ctx => isDeployPhase(ctx), canResolve: ctx => hasFieldSpace(ctx) && hasDeck(ctx, isRulerMonster), cost: ctx => applyMiracleTax(ctx, 'jibaeja'), resolve(ctx) { const r = summonFromDeck(ctx, isRulerMonster, 'rulerWater2Summon'); dispatchPending(ctx); return r; } }));
  add(mk({ id: 'ruler-fire-2-field-search', cardId: '화원소의 지배자', effectNo: 2, type: EFFECT_TYPES.ACTIVATION, zones: [ZONES.FIELD], timing: TIMING.MY_DEPLOY, tags: [TAGS.DECK_SEARCH], oncePerTurn: { key: '화원소의 지배자_2', limit: 1 }, condition: ctx => isDeployPhase(ctx), canResolve: ctx => hasDeck(ctx, isRulerMonster), cost: ctx => applyMiracleTax(ctx, 'jibaeja'), resolve(ctx) { const r = searchToHand(ctx, isRulerMonster, 'rulerFire2Search', true); dispatchPending(ctx); return r; } }));
  add(mk({ id: 'ruler-electric-2-on-summon-search-two', cardId: '전원소의 지배자', effectNo: 2, type: EFFECT_TYPES.TRIGGER, zones: [ZONES.FIELD], events: [EVENTS.SUMMON], timing: TIMING.ON_SUMMON, tags: [TAGS.DECK_SEARCH, TAGS.DRAW], oncePerTurn: { key: '전원소의 지배자_2', limit: 1 }, condition: ctx => eventCardIs(ctx, '전원소의 지배자'), canResolve: ctx => hasDeck(ctx, isJibaejaCard) || hasDeck(ctx, isJibaeryongCard), cost: ctx => applyMiracleTax(ctx, 'jibaeja'), resolve(ctx) { const r1 = searchToHand(ctx, isJibaejaCard, 'rulerElectric2SearchJibaeja', true); const r2 = searchToHand(ctx, isJibaeryongCard, 'rulerElectric2SearchJibaeryong', true); afterDrawOptional(ctx); dispatchPending(ctx); return { ok: !!(r1.ok || r2.ok), r1, r2 }; } }));
  add(mk({ id: 'ruler-wind-2-grave-send-dragon-revive', cardId: '풍원소의 지배자', effectNo: 2, type: EFFECT_TYPES.QUICK, zones: [ZONES.GRAVE], timing: TIMING.EITHER_TURN, tags: [TAGS.COST_SEND_TO_GRAVE, TAGS.GRAVE_SUMMON, TAGS.DRAW], oncePerTurn: { key: '풍원소의 지배자_2', limit: 1 }, condition: ctx => grave(ctx).some(c => getCardId(c) === '풍원소의 지배자'), canResolve: ctx => hasFieldSpace(ctx) && hasDeck(ctx, isDragonMonster) && grave(ctx).some(c => getCardId(c) === '풍원소의 지배자'), cost: ctx => applyMiracleTax(ctx, 'jibaeja'), resolve(ctx) { const dump = sendDeckToGrave(ctx, isDragonMonster, 'rulerWind2DumpDragon'); const summon = moveSummon(ctx, '풍원소의 지배자', ZONES.GRAVE, 'rulerWind2Revive'); afterDrawOptional(ctx); dispatchPending(ctx); return { ok: dump.ok && summon.ok, dump, summon }; } }));

  RULER_IDS.forEach(id => add(mk({ id: `${id}-3-field-summon-dragon-discard`, cardId: id, effectNo: 3, type: EFFECT_TYPES.ACTIVATION, zones: [ZONES.FIELD], timing: TIMING.MY_DEPLOY, tags: [TAGS.DECK_SUMMON, TAGS.DISCARD_HAND], oncePerTurn: { key: `${id}_3`, limit: 1 }, text: '자신 전개 단계에 덱에서 지배룡 몬스터 1장을 소환하고 패를 1장 버린다.', condition: ctx => isDeployPhase(ctx), canResolve: ctx => hasFieldSpace(ctx) && hasDeck(ctx, isDragonMonster) && hand(ctx).length > 0, cost: ctx => applyMiracleTax(ctx, 'jibaeja'), resolve(ctx) { const summon = summonFromDeck(ctx, isDragonMonster, 'rulerCommon3SummonDragon'); const discard = discardFirst(ctx, null, 'rulerCommon3Discard'); dispatchPending(ctx); return { ok: summon.ok && discard.ok, summon, discard }; } })));

  // ── 지배룡 4종 ─────────────────────────────
  add(mk({ id: 'dragon-water-1-nonhand-grave-recover', cardId: '수원소의 지배룡', effectNo: 1, type: EFFECT_TYPES.TRIGGER, zones: [ZONES.GRAVE], events: [EVENTS.SENT_TO_GRAVE], timing: TIMING.ON_SENT_TO_GRAVE, tags: [TAGS.DECK_SEARCH || 'recover'], oncePerTurn: { key: '수원소의 지배룡_1', limit: 1 }, condition: ctx => eventCardIs(ctx, '수원소의 지배룡') && eventFromNotHand(ctx), canResolve: ctx => grave(ctx).some(c => isJibaeMonster(c) && getCardId(c) !== '수원소의 지배룡'), cost: ctx => applyMiracleTax(ctx, 'jibaeryong'), resolve(ctx) { const target = firstOrSelected(ctx, grave(ctx), c => isJibaeMonster(c) && getCardId(c) !== '수원소의 지배룡'); const r = moveAddToHand(ctx, target, ZONES.GRAVE, 'dragonWater1Recover', true); dispatchPending(ctx); return r; } }));
  add(mk({ id: 'dragon-fire-1-nonhand-grave-negate-field', cardId: '화원소의 지배룡', effectNo: 1, type: EFFECT_TYPES.TRIGGER, zones: [ZONES.GRAVE], events: [EVENTS.SENT_TO_GRAVE], timing: TIMING.ON_SENT_TO_GRAVE, tags: [TAGS.NEGATE_EFFECT], oncePerTurn: { key: '화원소의 지배룡_1', limit: 1 }, condition: ctx => eventCardIs(ctx, '화원소의 지배룡') && eventFromNotHand(ctx), canResolve: ctx => opponentFieldCards(ctx).length > 0, cost: ctx => applyMiracleTax(ctx, 'jibaeryong'), resolve(ctx) { const target = firstOrSelected(ctx, opponentFieldCards(ctx)); const ok = negateFieldCard(target); dispatchPending(ctx); return { ok, target: getCardId(target) }; } }));
  add(mk({ id: 'dragon-electric-1-nonhand-grave-draw-two', cardId: '전원소의 지배룡', effectNo: 1, type: EFFECT_TYPES.TRIGGER, zones: [ZONES.GRAVE], events: [EVENTS.SENT_TO_GRAVE], timing: TIMING.ON_SENT_TO_GRAVE, tags: [TAGS.DRAW], oncePerTurn: { key: '전원소의 지배룡_1', limit: 1 }, condition: ctx => eventCardIs(ctx, '전원소의 지배룡') && eventFromNotHand(ctx), canResolve: ctx => canDraw(ctx, 2), cost: ctx => applyMiracleTax(ctx, 'jibaeryong'), resolve(ctx) { const r = draw(ctx, 2); dispatchPending(ctx); return r; } }));
  add(mk({ id: 'dragon-wind-1-nonhand-grave-summon-two-dragons', cardId: '풍원소의 지배룡', effectNo: 1, type: EFFECT_TYPES.TRIGGER, zones: [ZONES.GRAVE], events: [EVENTS.SENT_TO_GRAVE], timing: TIMING.ON_SENT_TO_GRAVE, tags: [TAGS.DECK_SUMMON], oncePerTurn: { key: '풍원소의 지배룡_1', limit: 1 }, condition: ctx => eventCardIs(ctx, '풍원소의 지배룡') && eventFromNotHand(ctx), canResolve: ctx => hasFieldSpace(ctx) && hasDeck(ctx, isDragonMonster), cost: ctx => applyMiracleTax(ctx, 'jibaeryong'), resolve(ctx) { const max = Math.min(2, deck(ctx).filter(isDragonMonster).length, 5 - field(ctx).length); const results = []; for (let i = 0; i < max; i += 1) results.push(summonFromDeck(ctx, isDragonMonster, 'dragonWind1Summon')); dispatchPending(ctx); return { ok: results.length > 0 && results.every(r => r.ok), results }; } }));
  DRAGON_IDS.forEach(id => add(mk({ id: `${id}-2-discarded-draw`, cardId: id, effectNo: 2, type: EFFECT_TYPES.TRIGGER, zones: [ZONES.GRAVE], events: [EVENTS.DISCARDED], timing: TIMING.NONE, tags: [TAGS.DRAW], oncePerTurn: { key: `${id}_2`, limit: 1 }, condition: ctx => eventCardIs(ctx, id), canResolve: ctx => canDraw(ctx, 1), cost: ctx => applyMiracleTax(ctx, 'jibaeryong'), resolve(ctx) { const r = draw(ctx, 1); dispatchPending(ctx); return r; } })));
  DRAGON_IDS.forEach(id => add(mk({ id: `${id}-3-field-send-self-discard-draw`, cardId: id, effectNo: 3, type: EFFECT_TYPES.ACTIVATION, zones: [ZONES.FIELD], timing: TIMING.MY_DEPLOY, tags: [TAGS.COST_SEND_TO_GRAVE, TAGS.COST_DISCARD, TAGS.DRAW], oncePerTurn: { key: `${id}_3`, limit: 1 }, text: '필드의 이 카드를 묘지로 보내고 패의 지배자/지배룡 카드를 버린 뒤 1장 드로우한다.', condition: () => true, canResolve: ctx => hand(ctx).some(c => isJibaejaCard(c) || isJibaeryongCard(c)) && canDraw(ctx, 1), cost(ctx) { const tax = applyMiracleTax(ctx, 'jibaeryong'); if (!tax.ok) return tax; const send = moveSendToGrave(ctx, id, ZONES.FIELD, 'dragon3CostSendSelf'); if (!send.ok) return send; const discard = discardFirst(ctx, c => isJibaejaCard(c) || isJibaeryongCard(c), 'dragon3CostDiscardJibae'); return { ok: send.ok && discard.ok, send, discard }; }, resolve(ctx) { const r = draw(ctx, 1); dispatchPending(ctx); return r; } })));

  // ── 사원소 키 카드 ─────────────────────────────
  add(mk({ id: 'sa-wonso-dragon-procedure', cardId: '사원소의 지배룡', effectNo: 0, type: EFFECT_TYPES.PROCEDURE, zones: [ZONES.HAND, ZONES.GRAVE], timing: TIMING.MY_DEPLOY, isActivated: false, summonProcedure: true, text: '카드명이 다른 지배룡 몬스터 4장을 제외하고 패/묘지에서 소환한다.', condition: ctx => noActiveChain() && isDeployPhase(ctx), canResolve: ctx => hasFieldSpace(ctx) && sameNameCountInFieldGraveExile(ctx, isDragonMonster) >= 4 && (hand(ctx).concat(grave(ctx)).some(c => getCardId(c) === '사원소의 지배룡')), resolve(ctx) { const mats = chooseTwo(ctx, uniqueMaterials(ctx, isDragonMonster)).concat(uniqueMaterials(ctx, isDragonMonster).filter(c => !chooseTwo(ctx, uniqueMaterials(ctx, isDragonMonster)).some(x => getCardId(x) === getCardId(c))).slice(0, 4 - chooseTwo(ctx, uniqueMaterials(ctx, isDragonMonster)).length)); if (mats.length < 4) return { ok: false, error: '지배룡 4종 부족' }; const banished = mats.slice(0, 4).map(c => removeMaterialById(ctx, getCardId(c), isDragonMonster)); const zone = hand(ctx).some(c => getCardId(c) === '사원소의 지배룡') ? ZONES.HAND : ZONES.GRAVE; const summon = moveSummon(ctx, '사원소의 지배룡', zone, 'saWonsoDragonProcedure'); dispatchPending(ctx); return { ok: banished.every(r => r.ok) && summon.ok, banished, summon }; } }));
  add(mk({ id: 'sa-wonso-ruler-procedure', cardId: '사원소의 지배자', effectNo: 0, type: EFFECT_TYPES.PROCEDURE, zones: [ZONES.HAND, ZONES.GRAVE], timing: TIMING.MY_DEPLOY, isActivated: false, summonProcedure: true, text: '카드명이 다른 지배자 몬스터 4장을 제외하고 패/묘지에서 소환한다.', condition: ctx => noActiveChain() && isDeployPhase(ctx), canResolve: ctx => hasFieldSpace(ctx) && sameNameCountInFieldGraveExile(ctx, isRulerMonster) >= 4 && (hand(ctx).concat(grave(ctx)).some(c => getCardId(c) === '사원소의 지배자')), resolve(ctx) { const mats = uniqueMaterials(ctx, isRulerMonster).slice(0, 4); if (mats.length < 4) return { ok: false, error: '지배자 4종 부족' }; const banished = mats.map(c => removeMaterialById(ctx, getCardId(c), isRulerMonster)); const zone = hand(ctx).some(c => getCardId(c) === '사원소의 지배자') ? ZONES.HAND : ZONES.GRAVE; const summon = moveSummon(ctx, '사원소의 지배자', zone, 'saWonsoRulerProcedure'); dispatchPending(ctx); return { ok: banished.every(r => r.ok) && summon.ok, banished, summon }; } }));

  add(mk({ id: 'sa-wonso-dragon-1-search-two-rulers', cardId: '사원소의 지배룡', effectNo: 1, type: EFFECT_TYPES.ACTIVATION, zones: [ZONES.FIELD], timing: TIMING.MY_DEPLOY, tags: [TAGS.DECK_SEARCH, TAGS.DISCARD_HAND], oncePerTurn: { key: '사원소의 지배룡_1', limit: 1 }, condition: ctx => isDeployPhase(ctx), canResolve: ctx => hasDeck(ctx, isRulerMonster), cost: ctx => applyMiracleTax(ctx, 'jibaeryong'), resolve(ctx) { const picks = chooseTwo(ctx, deck(ctx).filter(isRulerMonster)); const added = picks.map(c => moveAddToHand(ctx, c, ZONES.DECK, 'saWonsoDragon1Search', true)); const disc = optionalDiscardLoop(ctx, 'saWonsoDragon1OptionalDiscard'); dispatchPending(ctx); return { ok: added.length > 0 && added.every(r => r.ok), added, disc }; } }));
  add(mk({ id: 'sa-wonso-ruler-1-search-two-dragons', cardId: '사원소의 지배자', effectNo: 1, type: EFFECT_TYPES.ACTIVATION, zones: [ZONES.FIELD], timing: TIMING.MY_DEPLOY, tags: [TAGS.DECK_SEARCH, TAGS.DISCARD_HAND], oncePerTurn: { key: '사원소의 지배자_1', limit: 1 }, condition: ctx => isDeployPhase(ctx), canResolve: ctx => hasDeck(ctx, isDragonMonster), cost: ctx => applyMiracleTax(ctx, 'jibaeja'), resolve(ctx) { const picks = chooseTwo(ctx, deck(ctx).filter(isDragonMonster)); const added = picks.map(c => moveAddToHand(ctx, c, ZONES.DECK, 'saWonsoRuler1Search', true)); const disc = optionalDiscardLoop(ctx, 'saWonsoRuler1OptionalDiscard'); dispatchPending(ctx); return { ok: added.length > 0 && added.every(r => r.ok), added, disc }; } }));
  add(mk({ id: 'sa-wonso-dragon-2-attack-boost', cardId: '사원소의 지배룡', effectNo: 2, type: EFFECT_TYPES.QUICK, zones: [ZONES.FIELD], timing: TIMING.EITHER_TURN, tags: ['attackModify'], oncePerTurn: { key: '사원소의 지배룡_2', limit: 1 }, condition: ctx => isAttackPhase(ctx), canResolve: ctx => hand(ctx).length < hand(ctx, opp(ctx)).length, cost: ctx => applyMiracleTax(ctx, 'jibaeryong'), resolve(ctx) { const self = field(ctx).find(c => getCardId(c) === '사원소의 지배룡'); if (!self) return { ok: false }; const diff = hand(ctx, opp(ctx)).length - hand(ctx).length; self.atk = (self.atk || getCardDef(self)?.atk || 4) + diff; dispatchPending(ctx); return { ok: true, diff }; } }));
  add(mk({ id: 'sa-wonso-dragon-3-negate-discard-two', cardId: '사원소의 지배룡', effectNo: 3, type: EFFECT_TYPES.QUICK, zones: [ZONES.FIELD], timing: TIMING.EITHER_TURN, tags: [TAGS.NEGATE_EFFECT, TAGS.DISCARD_HAND], oncePerTurn: { key: '사원소의 지배룡_3', limit: 1 }, condition: ctx => !!ctx.chainLink, canResolve: ctx => hand(ctx).length <= 5 && hand(ctx).length >= 2, cost: ctx => applyMiracleTax(ctx, 'jibaeryong'), resolve(ctx) { if (ctx.chainLink) { ctx.chainLink.negated = true; ctx.chainLink.isNegated = true; ctx.chainLink.negatedBy = '사원소의 지배룡'; } const d1 = discardFirst(ctx, null, 'saWonsoDragon3Discard1'); const d2 = discardFirst(ctx, null, 'saWonsoDragon3Discard2'); dispatchPending(ctx); return { ok: d1.ok && d2.ok, d1, d2 }; } }));
  add(mk({ id: 'sa-wonso-ruler-2-banish-self-revive-two', cardId: '사원소의 지배자', effectNo: 2, type: EFFECT_TYPES.QUICK, zones: [ZONES.FIELD], timing: TIMING.EITHER_TURN, tags: [TAGS.COST_BANISH, TAGS.GRAVE_SUMMON, TAGS.EXILE_SUMMON], oncePerTurn: { key: '사원소의 지배자_2', limit: 1 }, condition: () => true, canResolve: ctx => hasFieldSpace(ctx) && graveExile(ctx, c => isRulerMonster(c) && getCardId(c) !== '사원소의 지배자').length + graveExile(ctx, c => isDragonMonster(c)).length > 0, cost(ctx) { const tax = applyMiracleTax(ctx, 'jibaeja'); if (!tax.ok) return tax; const st = stateOf(ctx); st.rulerSaWonsoReturnAtEnd = true; const self = field(ctx).find(c => getCardId(c) === '사원소의 지배자'); if (self) { st._rulerSaWonsoSavedAtk = self.atk; st._rulerSaWonsoSavedAtkBase = self.atkBase; } return moveBanish(ctx, '사원소의 지배자', ZONES.FIELD, 'saWonsoRuler2BanishSelf'); }, resolve(ctx) { const results = []; const ja = firstOrSelected(ctx, graveExile(ctx, c => isRulerMonster(c) && getCardId(c) !== '사원소의 지배자')); if (ja && hasFieldSpace(ctx)) results.push(summonFromGraveExile(ctx, c => getCardId(c) === getCardId(ja), 'saWonsoRuler2SummonRuler')); const dr = firstOrSelected(ctx, graveExile(ctx, isDragonMonster)); if (dr && hasFieldSpace(ctx)) results.push(summonFromGraveExile(ctx, c => getCardId(c) === getCardId(dr), 'saWonsoRuler2SummonDragon')); dispatchPending(ctx); return { ok: results.length > 0 && results.every(r => r.ok), results }; } }));
  add(mk({ id: 'sa-wonso-ruler-3-send-op-field-discard', cardId: '사원소의 지배자', effectNo: 3, type: EFFECT_TYPES.QUICK, zones: [ZONES.FIELD], timing: TIMING.EITHER_TURN, tags: [TAGS.TARGET_OPPONENT_FIELD || 'targetOpponentField', TAGS.COST_DISCARD], oncePerTurn: { key: '사원소의 지배자_3', limit: 1 }, condition: ctx => isDeployPhase(ctx), canResolve: ctx => hand(ctx).length <= 5 && hand(ctx).length >= 1 && opponentFieldCards(ctx).length > 0, cost: ctx => applyMiracleTax(ctx, 'jibaeja'), resolve(ctx) { const target = firstOrSelected(ctx, opponentFieldCards(ctx)); const zone = field(ctx, opp(ctx)).some(c => getCardId(c) === getCardId(target)) ? ZONES.FIELD : ZONES.FIELD_ZONE; const send = zone === ZONES.FIELD ? moveSendToGrave(ctx, target, ZONES.FIELD, 'saWonsoRuler3SendOpponent', opp(ctx)) : ctx.move.removeFieldCard({ controller: opp(ctx), reason: 'saWonsoRuler3RemoveOpponentFieldCard' }); const discard = discardFirst(ctx, null, 'saWonsoRuler3Discard'); dispatchPending(ctx); return { ok: !!send.ok && discard.ok, send, discard }; } }));

  // ── 마법/함정 ─────────────────────────────
  add(mk({ id: 'ruler-miracle-1-send-four-kinds', cardId: '사원소의 기적', effectNo: 1, type: EFFECT_TYPES.ACTIVATION, zones: [ZONES.HAND], timing: TIMING.MY_DEPLOY, tags: [TAGS.COST_SEND_TO_GRAVE], oncePerTurn: { scope: 'game', key: '사원소의 기적_1', limit: 1 }, text: '덱에서 카드명이 다른 지배자 또는 지배룡 4종을 묘지로 보내고, 이 턴 해당 계열 효과 발동마다 패 1장을 버리게 한다.', condition: () => true, canResolve: ctx => deck(ctx).filter(isRulerMonster).map(getCardId).filter((v, i, a) => a.indexOf(v) === i).length >= 4 || deck(ctx).filter(isDragonMonster).map(getCardId).filter((v, i, a) => a.indexOf(v) === i).length >= 4, resolve(ctx) { const chooseDragon = ctx && (ctx.choice === 'jibaeryong' || ctx.selectedType === 'jibaeryong'); const pred = chooseDragon ? isDragonMonster : isRulerMonster; const uniq = Array.from(new Map(deck(ctx).filter(pred).map(c => [getCardId(c), c])).values()).slice(0, 4); const results = uniq.map(c => moveSendToGrave(ctx, c, ZONES.DECK, 'rulerMiracleSendFour')); const st = stateOf(ctx); st.rulerMiracleActive = true; st.rulerMiracleType = chooseDragon ? 'jibaeryong' : 'jibaeja'; const self = hand(ctx).some(c => getCardId(c) === '사원소의 기적') ? moveSendToGrave(ctx, '사원소의 기적', ZONES.HAND, 'rulerMiracleResolved') : { ok: true }; dispatchPending(ctx); return { ok: results.length === 4 && results.every(r => r.ok), results, self }; } }));
  add(mk({ id: 'ruler-chain-1-discarded-draw-up-to-count', cardId: '지배의 사슬', effectNo: 1, type: EFFECT_TYPES.TRIGGER, zones: [ZONES.HAND], events: [EVENTS.DISCARDED], timing: TIMING.NONE, tags: [TAGS.DRAW], oncePerTurn: { key: '지배의 사슬_1', limit: 1 }, condition: ctx => hand(ctx).some(c => getCardId(c) === '지배의 사슬'), canResolve: ctx => canDraw(ctx, 1), resolve(ctx) { const st = stateOf(ctx); st.rulerDiscardedThisTurn = (st.rulerDiscardedThisTurn || 0) + 1; const n = Math.min(st.rulerDiscardedThisTurn, deck(ctx).length); const r = draw(ctx, n); dispatchPending(ctx); return r; } }));
  add(mk({ id: 'ruler-chain-2-grave-banish-return-exile-draw', cardId: '지배의 사슬', effectNo: 2, type: EFFECT_TYPES.QUICK, zones: [ZONES.GRAVE], timing: TIMING.EITHER_TURN, tags: [TAGS.COST_BANISH, TAGS.DRAW], oncePerTurn: { key: '지배의 사슬_2', limit: 1 }, condition: ctx => !isMyTurnFallback(ctx), canResolve: ctx => grave(ctx).some(c => getCardId(c) === '지배의 사슬') && exile(ctx).length > 0 && canDraw(ctx, 1), cost: ctx => moveBanish(ctx, '지배의 사슬', ZONES.GRAVE, 'rulerChain2Cost'), resolve(ctx) { const count = Math.min(8, exile(ctx).length); const returned = exile(ctx).splice(0, count); deck(ctx).push(...returned); draw(ctx, 1); dispatchPending(ctx); return { ok: true, returned: count }; } }));
  add(mk({ id: 'ruler-spell-1-attack-phase-scale-effects', cardId: '지배룡과 지배자', effectNo: 1, type: EFFECT_TYPES.QUICK, zones: [ZONES.HAND], timing: TIMING.EITHER_TURN, tags: [TAGS.COST_DISCARD, 'attackModify'], oncePerTurn: { key: '지배룡과 지배자_1', limit: 1 }, condition: ctx => isAttackPhase(ctx), canResolve: ctx => hand(ctx).some(c => getCardId(c) === '지배룡과 지배자') && field(ctx).length > 0, cost: () => ({ ok: true }), resolve(ctx) { const before = hand(ctx).length; const send = moveSendToGrave(ctx, '지배룡과 지배자', ZONES.HAND, 'rulerSpell1Resolve'); const count = Math.max(0, before - 1); if (count <= 5) { const t = firstOrSelected(ctx, field(ctx), isMonster); if (t) t.atk = (t.atk || getCardDef(t)?.atk || 0) + 2; } if (count <= 4) field(ctx).filter(isMonster).forEach(c => { c.atk = (c.atk || getCardDef(c)?.atk || 0) + 1; }); if (count <= 3) { const op = firstOrSelected(ctx, field(ctx, opp(ctx)), isMonster); if (op) op.atk = (op.atk || getCardDef(op)?.atk || 0) - 3; } if (count <= 2) protectAttackPhase(ctx); dispatchPending(ctx); return { ok: send.ok, handCount: count }; } }));
  add(mk({ id: 'ruler-spell-2-grave-banish-draw', cardId: '지배룡과 지배자', effectNo: 2, type: EFFECT_TYPES.QUICK, zones: [ZONES.GRAVE], timing: TIMING.EITHER_TURN, tags: [TAGS.COST_BANISH, TAGS.DRAW], oncePerTurn: { key: '지배룡과 지배자_2', limit: 1 }, condition: () => true, canResolve: ctx => grave(ctx).some(c => getCardId(c) === '지배룡과 지배자') && canDraw(ctx, 1), cost: ctx => moveBanish(ctx, '지배룡과 지배자', ZONES.GRAVE, 'rulerSpell2Cost'), resolve(ctx) { const r = draw(ctx, 1); dispatchPending(ctx); return r; } }));

  const registered = registry.registerEffects(effects);
  registry.syncEffectIdsToCards();

  function getRulerEffectIds() { return effects.map(e => e.id); }
  function getRulerCards() { return ALL_IDS.slice(); }
  function getRulerImplementationSpec() {
    return Object.freeze({
      phase: '16-5 ruler/jibaeryong correction',
      cards: ALL_IDS,
      effectCount: effects.length,
      criticalChecks: Object.freeze([
        '지배자/지배룡 서치·소환·드로우는 canResolve에서 발동 전 차단한다.',
        '사원소의 지배자/지배룡 자체 소환은 procedure이며 체인을 만들지 않는다.',
        '지배룡 ①은 패 이외에서 묘지로 보내졌을 때만 유발한다.',
        '지배룡 ②는 버려졌을 때만 유발한다.',
        '사원소의 기적은 이후 해당 계열 효과 발동마다 패 1장 추가 코스트를 요구한다.',
      ]),
    });
  }

  global.HB_RULER_EFFECTS = Object.freeze({
    effects: registered,
    getRulerEffectIds,
    getRulerCards,
    getRulerImplementationSpec,
    isJibaejaCard,
    isJibaeryongCard,
    isRulerMonster,
    isDragonMonster,
    uniqueMaterials,
  });
})(window);
